### ISSUE TITLE
false negative when running use-apphost-from-sdk

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-bunny#25]
`use-apphost-from-sdk` fails if it's the only test being executed, but passes if it's executed along with other tests in the `dotnet-regular-tests` test suite.

This results in a false negative and hides real issues.

I suspect some state is leaking, such as a non-empty nuget directory containing working nuget artifacts, which works-around and hides the underlying issue.

**Comment by nicrowe00** [comment]
`use-apphost-from-sdk` no longer fails if it is the only test being executed.
