### ISSUE TITLE
Support building and running on aarch64 (aka arm64)

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-bunny#30]
We only build this test runner and publish releases for x86_64 (aka x64). We should look into adding support for other architectures such as aarch64 (aka arm64) so we can make use of this runner on those architectures too.

**Comment by RheaAyase** [comment]
How would you want to do releases, keep x64 as `turkey` and add `turkey-aarch64` ? To not have to modify all the CI configurations?

**Comment by omajid** [comment]
Yeah, that's probably the safest thing to do for now.

Longer term, maybe we should think about publishing everything as `turkey-$(uname -m)` (`turkey-x86_64`, `turkey-aarch64`)?

**Comment by omajid** [comment]
PR: https://github.com/redhat-developer/dotnet-bunny/pull/31

**Comment by omajid** [comment]
With `v6` out, I think we can close this.
