### ISSUE TITLE
`dotnet test` occasionally hangs

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-bunny#39]
When I run `dotnet test` a couple of times against `Turkey.Tests`, occasionally it hangs with this output:
```
$ dotnet test
Test run for /home/tmds/repos/dotnet-bunny/Turkey.Tests/bin/Debug/netcoreapp3.1/Turkey.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0-dev+55e7e45431c9c05656c999b902686e7402664573
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
^[[55;1R^[[55;9R
```

A quick look with lldb shows the test runner is reading standard in as part of determining the cursor position. Probably the characters being printed are the cursor position. This needs more investigation.

Probably this is not happening in our CI runs because there is no tty allocated(?), which causes the cursor position to no-op.

**Environment**
dotnet 3.1.104 on Fedora 32.
dotnet bunny at 9a54e91eabaa49457d32d14b36f5ffd2b40b9b04

cc @omajid @RheaAyase

**Comment by RheaAyase** [comment]
We don't have CI that would run tests for this project at all.

**Comment by tmds** [comment]
After further investigation, I created a .NET Core issue for this: https://github.com/dotnet/runtime/issues/42247.

**Comment by tmds** [comment]
Closing since there is nothing to do on dotnet-bunny side.
