### ISSUE TITLE
Packages with vulnerabilities have been detected: Newtonsoft.Json 12.0.1 is vulnerable

### ISSUE THREAD

**Issue by RadekCap** [redhat-developer/dotnet-bunny#72]
Newtonsoft.Json prior to version 13.0.1 is vulnerable to Insecure Defaults due to improper handling of StackOverFlow exception (SOE) whenever nested expressions are being processed.

See https://devhub.checkmarx.com/cve-details/Cx46691637-14e8/

**Comment by tmds** [comment]
There's a PR to bump the version: https://github.com/redhat-developer/dotnet-bunny/pull/63.

cc @omajid

**Comment by omajid** [comment]
Closing since https://github.com/redhat-developer/dotnet-bunny/pull/63 is merged.
